# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/mainWindow.ui'
#
# Created: Fri Feb 14 04:56:27 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 555)
		MainWindow.setUnifiedTitleAndToolBarOnMac(True)
		self.horizontalSplit = QtGui.QWidget(MainWindow)
		self.horizontalSplit.setObjectName("horizontalSplit")
		self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalSplit)
		self.horizontalLayout.setSpacing(0)
		self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.splitter = QtGui.QSplitter(self.horizontalSplit)
		self.splitter.setLineWidth(1)
		self.splitter.setOrientation(QtCore.Qt.Horizontal)
		self.splitter.setObjectName("splitter")
		self.listComics = QtGui.QListView(self.splitter)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.listComics.sizePolicy().hasHeightForWidth())
		self.listComics.setSizePolicy(sizePolicy)
		self.listComics.setAlternatingRowColors(True)
		self.listComics.setIconSize(QtCore.QSize(64, 64))
		self.listComics.setObjectName("listComics")
		self.listIssues = QtGui.QListView(self.splitter)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.listIssues.sizePolicy().hasHeightForWidth())
		self.listIssues.setSizePolicy(sizePolicy)
		self.listIssues.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
		self.listIssues.setIconSize(QtCore.QSize(128, 128))
		self.listIssues.setMovement(QtGui.QListView.Static)
		self.listIssues.setResizeMode(QtGui.QListView.Adjust)
		self.listIssues.setViewMode(QtGui.QListView.IconMode)
		self.listIssues.setObjectName("listIssues")
		self.horizontalLayout.addWidget(self.splitter)
		MainWindow.setCentralWidget(self.horizontalSplit)
		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
		self.menubar.setDefaultUp(False)
		self.menubar.setObjectName("menubar")
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		self.menuHelp = QtGui.QMenu(self.menubar)
		self.menuHelp.setObjectName("menuHelp")
		self.menuAction = QtGui.QMenu(self.menubar)
		self.menuAction.setObjectName("menuAction")
		self.menuSeries = QtGui.QMenu(self.menubar)
		self.menuSeries.setObjectName("menuSeries")
		self.menuIssue = QtGui.QMenu(self.menubar)
		self.menuIssue.setObjectName("menuIssue")
		MainWindow.setMenuBar(self.menubar)
		self.toolBar = QtGui.QToolBar(MainWindow)
		self.toolBar.setMovable(False)
		self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolBar.setFloatable(False)
		self.toolBar.setObjectName("toolBar")
		MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
		self.statusBar = QtGui.QStatusBar(MainWindow)
		self.statusBar.setSizeGripEnabled(False)
		self.statusBar.setObjectName("statusBar")
		MainWindow.setStatusBar(self.statusBar)
		self.menuFileSettings = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/res/tango/preferences-system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.menuFileSettings.setIcon(icon)
		self.menuFileSettings.setObjectName("menuFileSettings")
		self.menuFileQuit = QtGui.QAction(MainWindow)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/res/tango/system-log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.menuFileQuit.setIcon(icon1)
		self.menuFileQuit.setObjectName("menuFileQuit")
		self.actionAdd_series = QtGui.QAction(MainWindow)
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/res/tango/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionAdd_series.setIcon(icon2)
		self.actionAdd_series.setObjectName("actionAdd_series")
		self.actionUpdate = QtGui.QAction(MainWindow)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/res/tango/view-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionUpdate.setIcon(icon3)
		self.actionUpdate.setObjectName("actionUpdate")
		self.actionAbout_MUComicLoad = QtGui.QAction(MainWindow)
		self.actionAbout_MUComicLoad.setObjectName("actionAbout_MUComicLoad")
		self.actionDownload = QtGui.QAction(MainWindow)
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(":/res/tango/go-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionDownload.setIcon(icon4)
		self.actionDownload.setObjectName("actionDownload")
		self.actionOpen = QtGui.QAction(MainWindow)
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(":/res/tango/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionOpen.setIcon(icon5)
		self.actionOpen.setObjectName("actionOpen")
		self.actionList_View = QtGui.QAction(MainWindow)
		self.actionList_View.setObjectName("actionList_View")
		self.actionFolder_View = QtGui.QAction(MainWindow)
		self.actionFolder_View.setObjectName("actionFolder_View")
		self.actionFav_series = QtGui.QAction(MainWindow)
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(":/res/tango/emblem-favorite.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.actionFav_series.setIcon(icon6)
		self.actionFav_series.setObjectName("actionFav_series")
		self.actionDownload_Series = QtGui.QAction(MainWindow)
		self.actionDownload_Series.setIcon(icon4)
		self.actionDownload_Series.setObjectName("actionDownload_Series")
		self.actionSeries_have_Cover = QtGui.QAction(MainWindow)
		self.actionSeries_have_Cover.setCheckable(True)
		self.actionSeries_have_Cover.setObjectName("actionSeries_have_Cover")
		self.actionDownload_Issue_As = QtGui.QAction(MainWindow)
		self.actionDownload_Issue_As.setIcon(icon4)
		self.actionDownload_Issue_As.setObjectName("actionDownload_Issue_As")
		self.menuFile.addAction(self.actionUpdate)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.menuFileSettings)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.menuFileQuit)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionAbout_MUComicLoad)
		self.menuAction.addAction(self.actionList_View)
		self.menuAction.addAction(self.actionFolder_View)
		self.menuAction.addSeparator()
		self.menuAction.addAction(self.actionSeries_have_Cover)
		self.menuSeries.addAction(self.actionAdd_series)
		self.menuSeries.addAction(self.actionDownload_Series)
		self.menuSeries.addAction(self.actionFav_series)
		self.menuIssue.addAction(self.actionOpen)
		self.menuIssue.addSeparator()
		self.menuIssue.addAction(self.actionDownload)
		self.menuIssue.addAction(self.actionDownload_Issue_As)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuAction.menuAction())
		self.menubar.addAction(self.menuSeries.menuAction())
		self.menubar.addAction(self.menuIssue.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())
		self.toolBar.addAction(self.actionUpdate)
		self.toolBar.addAction(self.actionAdd_series)
		self.toolBar.addAction(self.actionFav_series)
		self.toolBar.addAction(self.actionDownload)
		self.toolBar.addAction(self.actionOpen)
		self.toolBar.addAction(self.menuFileSettings)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MUComicLoad", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
		self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
		self.menuAction.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
		self.menuSeries.setTitle(QtGui.QApplication.translate("MainWindow", "Series", None, QtGui.QApplication.UnicodeUTF8))
		self.menuIssue.setTitle(QtGui.QApplication.translate("MainWindow", "Issue", None, QtGui.QApplication.UnicodeUTF8))
		self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFileSettings.setText(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFileQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdd_series.setText(QtGui.QApplication.translate("MainWindow", "&Add series", None, QtGui.QApplication.UnicodeUTF8))
		self.actionUpdate.setText(QtGui.QApplication.translate("MainWindow", "&Update", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAbout_MUComicLoad.setText(QtGui.QApplication.translate("MainWindow", "&About MUComicLoad", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDownload.setText(QtGui.QApplication.translate("MainWindow", "Download Issue", None, QtGui.QApplication.UnicodeUTF8))
		self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Read Issue", None, QtGui.QApplication.UnicodeUTF8))
		self.actionList_View.setText(QtGui.QApplication.translate("MainWindow", "&List View", None, QtGui.QApplication.UnicodeUTF8))
		self.actionFolder_View.setText(QtGui.QApplication.translate("MainWindow", "&Folder View", None, QtGui.QApplication.UnicodeUTF8))
		self.actionFav_series.setText(QtGui.QApplication.translate("MainWindow", "Fav series", None, QtGui.QApplication.UnicodeUTF8))
		self.actionFav_series.setToolTip(QtGui.QApplication.translate("MainWindow", "Fav series", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDownload_Series.setText(QtGui.QApplication.translate("MainWindow", "Download Series", None, QtGui.QApplication.UnicodeUTF8))
		self.actionSeries_have_Cover.setText(QtGui.QApplication.translate("MainWindow", "Series have Cover", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDownload_Issue_As.setText(QtGui.QApplication.translate("MainWindow", "Download Issue As ...", None, QtGui.QApplication.UnicodeUTF8))

import MUComic.mucomicload_rc
