# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/mainWindow.ui'
#
# Created: Wed Feb 12 05:46:48 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(800, 600)
		MainWindow.setUnifiedTitleAndToolBarOnMac(True)
		self.horizontalSplit = QtGui.QWidget(MainWindow)
		self.horizontalSplit.setObjectName("horizontalSplit")
		self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalSplit)
		self.horizontalLayout.setSpacing(0)
		self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.splitter = QtGui.QSplitter(self.horizontalSplit)
		self.splitter.setLineWidth(1)
		self.splitter.setOrientation(QtCore.Qt.Horizontal)
		self.splitter.setObjectName("splitter")
		self.listComics = QtGui.QListView(self.splitter)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.listComics.sizePolicy().hasHeightForWidth())
		self.listComics.setSizePolicy(sizePolicy)
		self.listComics.setAlternatingRowColors(True)
		self.listComics.setIconSize(QtCore.QSize(64, 64))
		self.listComics.setObjectName("listComics")
		self.listIssues = QtGui.QListView(self.splitter)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.listIssues.sizePolicy().hasHeightForWidth())
		self.listIssues.setSizePolicy(sizePolicy)
		self.listIssues.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
		self.listIssues.setIconSize(QtCore.QSize(128, 128))
		self.listIssues.setMovement(QtGui.QListView.Static)
		self.listIssues.setResizeMode(QtGui.QListView.Adjust)
		self.listIssues.setViewMode(QtGui.QListView.IconMode)
		self.listIssues.setObjectName("listIssues")
		self.horizontalLayout.addWidget(self.splitter)
		MainWindow.setCentralWidget(self.horizontalSplit)
		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
		self.menubar.setDefaultUp(False)
		self.menubar.setObjectName("menubar")
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		self.menuHelp = QtGui.QMenu(self.menubar)
		self.menuHelp.setObjectName("menuHelp")
		MainWindow.setMenuBar(self.menubar)
		self.toolBar = QtGui.QToolBar(MainWindow)
		self.toolBar.setMovable(False)
		self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolBar.setFloatable(False)
		self.toolBar.setObjectName("toolBar")
		MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
		self.statusBar = QtGui.QStatusBar(MainWindow)
		self.statusBar.setSizeGripEnabled(False)
		self.statusBar.setObjectName("statusBar")
		MainWindow.setStatusBar(self.statusBar)
		self.menuFileSettings = QtGui.QAction(MainWindow)
		icon = QtGui.QIcon.fromTheme('preferences-system',QtGui.QIcon(":/res/settings.png"))
		self.menuFileSettings.setIcon(icon)
		self.menuFileSettings.setObjectName("menuFileSettings")
		self.menuFileQuit = QtGui.QAction(MainWindow)
		icon1 = QtGui.QIcon.fromTheme('application-exit',QtGui.QICon(":/res/exit.png"))
		self.menuFileQuit.setIcon(icon1)
		self.menuFileQuit.setObjectName("menuFileQuit")
		self.actionAdd_series = QtGui.QAction(MainWindow)
		icon2 = QtGui.QIcon.fromTheme('list-add',QtGui.QIcon(":/res/addseries.png"))
		self.actionAdd_series.setIcon(icon2)
		self.actionAdd_series.setObjectName("actionAdd_series")
		self.actionUpdate = QtGui.QAction(MainWindow)
		icon3 = QtGui.QIcon.fromTheme('view-refresh',QtGui.QIcon(":/res/update.png"))
		self.actionUpdate.setIcon(icon3)
		self.actionUpdate.setObjectName("actionUpdate")
		self.actionAbout_MUComicLoad = QtGui.QAction(MainWindow)
		self.actionAbout_MUComicLoad.setObjectName("actionAbout_MUComicLoad")
		self.actionDownload = QtGui.QAction(MainWindow)
		icon4 = QtGui.QIcon.fromTheme('go-bottom',QtGui.QIcon(":/res/download.png"))
		self.actionDownload.setIcon(icon4)
		self.actionDownload.setObjectName("actionDownload")
		self.menuFile.addAction(self.actionUpdate)
		self.menuFile.addAction(self.actionAdd_series)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.menuFileSettings)
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.menuFileQuit)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionAbout_MUComicLoad)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())
		self.toolBar.addAction(self.actionUpdate)
		self.toolBar.addAction(self.actionAdd_series)
		self.toolBar.addAction(self.actionDownload)
		self.toolBar.addAction(self.menuFileSettings)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MUComicLoad", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
		self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
		self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFileSettings.setText(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFileQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdd_series.setText(QtGui.QApplication.translate("MainWindow", "&Add series", None, QtGui.QApplication.UnicodeUTF8))
		self.actionUpdate.setText(QtGui.QApplication.translate("MainWindow", "&Update", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAbout_MUComicLoad.setText(QtGui.QApplication.translate("MainWindow", "&About MUComicLoad", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDownload.setText(QtGui.QApplication.translate("MainWindow", "Download", None, QtGui.QApplication.UnicodeUTF8))

import MUComic.mucomicload_rc
