#!/usr/bin/env python3
from MUComicLoad.Database import DB
from MUComicLoad.startUI import UIStarter
import argparse
import configparser
import os.path

if __name__ == "__main__":
	conf_parser = argparse.ArgumentParser(
			add_help = False
			)
	conf_parser.add_argument("--config", "-c",
				help="Specify config file", metavar="FILE")
	args, remaining_argv = conf_parser.parse_known_args()
	config = configparser.ConfigParser()
	config.add_section("MUComicLoad")
	cfiles = []

	if os.path.isfile("/etc/mucomicload.conf"):
		cfiles.append("/etc/mucomicload.conf")
	if os.path.isfile(os.path.expanduser("~/.config/mucomicload.conf")):
		cfiles.append(os.path.expanduser("~/.config/mucomicload.conf"))
	if args.config and os.path.isfile(args.config):
		cfiles.append(args.config)
	config.set("MUComicLoad", "downloaddir", os.path.realpath("."))	
	config.set("MUComicLoad", "database", os.path.expanduser("~/.mucomics.db"))	
	config.read(cfiles)
	

	parser = argparse.ArgumentParser()
	parser.add_argument("--database", "-db")
	parser.add_argument("--config", "-c")

	args = parser.parse_args(remaining_argv)

	db = DB(config['MUComicLoad']['database'])

	app = UIStarter(db, None)

